### ISSUE TITLE
テーブルの枠組みを半自動で作れるようにしたい

### ISSUE THREAD

**Issue by d-tsuji** [future-architect/go-exceltesting#21]
## 背景

* テーブル物理名からカラムの枠組みを作成する必要がある（型は不要になっている）
  * 属性
  * 項目名
  * 項目物理名
* これらの項目がCLIなどの簡易ツール実行により、半自動で項目を埋められるようにしたい

![image](https://user-images.githubusercontent.com/24369487/189012821-79b32361-e8d9-4b5b-8109-35cfd4f8f8b6.png)

## TODO

* DBのカタログから情報を取得する
* 更新する方針は要検討。以下のような方針が考えられる
  * クリップボードにコピーして、貼り付けてもらう
  * ツール側でExcelを直接更新する

**Comment by ma91n** [comment]
done
